// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20231001110403_Add Payment and balance table modification")]
    partial class AddPaymentandbalancetablemodification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("remainBalance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("Core.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Core.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.DeliveryMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("deliveryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderStatusTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusTypeId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b73b1c4-5df9-4866-b29c-5762fd947d4c"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4063),
                            Name = "Order Progression-1",
                            OrderStatusTypeId = new Guid("05310e10-8742-4975-83e7-d85607871fb1"),
                            Status = "Pending",
                            StatusCode = "101",
                            StatusMessage = "Order is pending",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4064)
                        },
                        new
                        {
                            Id = new Guid("2d06f1fa-2e2b-4fde-952e-4c021c561f4f"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4068),
                            Name = "Order Progression-2",
                            OrderStatusTypeId = new Guid("05310e10-8742-4975-83e7-d85607871fb1"),
                            Status = "Processing",
                            StatusCode = "102",
                            StatusMessage = "Order is processing",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4068)
                        },
                        new
                        {
                            Id = new Guid("36587c38-bdaf-4876-a7e6-464e9bd9e3eb"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4071),
                            Name = "Order Progression-3",
                            OrderStatusTypeId = new Guid("05310e10-8742-4975-83e7-d85607871fb1"),
                            Status = "Shipped",
                            StatusCode = "103",
                            StatusMessage = "Order is shipped",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4071)
                        },
                        new
                        {
                            Id = new Guid("2b853889-81ca-4093-bdef-36a638958aac"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4073),
                            Name = "Order Progression-4",
                            OrderStatusTypeId = new Guid("05310e10-8742-4975-83e7-d85607871fb1"),
                            Status = "Delivered",
                            StatusCode = "104",
                            StatusMessage = "Order is delivered",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4074)
                        },
                        new
                        {
                            Id = new Guid("23bbc471-55fb-4003-921d-5a591c3cd55c"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4076),
                            Name = "Order Progression-5",
                            OrderStatusTypeId = new Guid("05310e10-8742-4975-83e7-d85607871fb1"),
                            Status = "Cancelled",
                            StatusCode = "105",
                            StatusMessage = "Order is cancelled",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4077)
                        },
                        new
                        {
                            Id = new Guid("e717f4b6-5a01-4a6b-9e2a-1250a0c21645"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4080),
                            Name = "Financial Transaction-1",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "Pending",
                            StatusCode = "201",
                            StatusMessage = "Financial transaction is pending",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4080)
                        },
                        new
                        {
                            Id = new Guid("19df71c3-460b-429e-9a89-a1fde8b01b52"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4083),
                            Name = "Financial Transaction-2",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "Processing",
                            StatusCode = "202",
                            StatusMessage = "Financial transaction is processing",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4083)
                        },
                        new
                        {
                            Id = new Guid("42e37bcb-e9a8-4979-9f7f-9f1e89921eb5"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4088),
                            Name = "Financial Transaction-3",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "Completed",
                            StatusCode = "203",
                            StatusMessage = "Financial transaction is completed",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4089)
                        },
                        new
                        {
                            Id = new Guid("2fc99977-7531-4091-8bd6-ca3884a909e2"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4091),
                            Name = "Financial Transaction-4",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "Cancelled",
                            StatusCode = "204",
                            StatusMessage = "Financial transaction is cancelled",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4091)
                        },
                        new
                        {
                            Id = new Guid("a054daef-7310-4f0c-bcde-c381f7ab86d4"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4094),
                            Name = "Authorization and Pay Mod-1",
                            OrderStatusTypeId = new Guid("1ffea1ba-230b-4b53-8cf0-8eda37d8c642"),
                            Status = "Verified",
                            StatusCode = "301",
                            StatusMessage = "Payment method verified",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4095)
                        },
                        new
                        {
                            Id = new Guid("d1c48752-7cce-42b1-8c74-7df91c74833c"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4097),
                            Name = "Payment Status-1",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "Paid",
                            StatusCode = "401",
                            StatusMessage = "Order Paid",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4098)
                        },
                        new
                        {
                            Id = new Guid("adc4c5bf-1a7f-4ba3-b24e-8ab4cf9c8075"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4100),
                            Name = "Payment Status-2",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "partially Paid",
                            StatusCode = "402",
                            StatusMessage = "Order Partially Paid",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4100)
                        },
                        new
                        {
                            Id = new Guid("dfc5b07a-7680-4617-bf98-ed61731ea491"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4102),
                            Name = "Payment Status-3",
                            OrderStatusTypeId = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            Status = "unPaid",
                            StatusCode = "403",
                            StatusMessage = "Order is UnPaid",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(4103)
                        });
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.OrderStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuseTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05310e10-8742-4975-83e7-d85607871fb1"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3936),
                            Description = "Order progression refers to the series of steps or stages that an order goes through from the moment it is placed until it is fulfilled or completed. This process is commonly associated with e-commerce, retail, manufacturing, and various other industries where goods or services are exchanged between a customer and a business.",
                            Name = "Order Progression",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3951)
                        },
                        new
                        {
                            Id = new Guid("a154a6dc-7802-4e15-a265-7fe45c8ca679"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3955),
                            Description = "A financial transaction refers to the exchange of funds or financial assets between two or more parties. These transactions are essential in the functioning of economies and businesses, enabling the flow of money, resources, and investments. Financial transactions can take many forms and serve various purposes, but they typically involve the transfer of money, securities, or other financial instruments.",
                            Name = "Financial Transaction",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3956)
                        },
                        new
                        {
                            Id = new Guid("1ffea1ba-230b-4b53-8cf0-8eda37d8c642"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3958),
                            Description = "Authorization and the Payment Module work together to create a secure and user-friendly experience. Authorization ensures that users have proper access, while the Payment Module facilitates hassle-free and secure transactions, making it convenient for customers to order and pay for their lunch",
                            Name = "Authorization and Pay Mod",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3958)
                        },
                        new
                        {
                            Id = new Guid("a74b2ca2-59ee-4d0a-986a-b75c3252a8d1"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3960),
                            Description = "Payment status refers to the state or condition of a financial transaction at a specific point in time. It provides information about whether a payment has been successfully completed, is pending, or has encountered issues. Payment status is important for both the payer and the payee as it indicates the outcome of a financial transaction.",
                            Name = "Payment Status",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3960)
                        },
                        new
                        {
                            Id = new Guid("9096c0b1-e08b-4fba-aa6e-fc27cabd414d"),
                            CreatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3973),
                            Description = "\"Review\" and \"Dispute\" are essential features that can enhance the user experience and address potential issues.",
                            Name = "Review and Dispute",
                            UpdatedAt = new DateTime(2023, 10, 1, 16, 34, 3, 99, DateTimeKind.Local).AddTicks(3974)
                        });
                });

            modelBuilder.Entity("Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Core.Entities.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");
                });

            modelBuilder.Entity("Core.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Core.Entities.Balance", b =>
                {
                    b.HasOne("Core.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Identity.User", b =>
                {
                    b.HasOne("Core.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.Order", b =>
                {
                    b.HasOne("Core.Entities.Identity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.OrderProduct", b =>
                {
                    b.HasOne("Core.Entities.OrderAggregate.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.OrderStatus", b =>
                {
                    b.HasOne("Core.Entities.OrderAggregate.OrderStatusType", "OrderStatusType")
                        .WithMany("OrderStatuses")
                        .HasForeignKey("OrderStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatusType");
                });

            modelBuilder.Entity("Core.Entities.Payment", b =>
                {
                    b.HasOne("Core.Entities.Identity.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Identity.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Core.Entities.OrderAggregate.OrderStatusType", b =>
                {
                    b.Navigation("OrderStatuses");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
